import {
  Star,
  Heart,
  Zap,
  Flame,
  Leaf,
  Droplet,
  Sun,
  Moon,
  Cloud,
  Snowflake,
  CircleCheck,
  CircleX,
  CircleAlert,
  CircleHelp,
  Flag,
  Bookmark,
  Pin,
  Tag,
  Paperclip,
  Folder,
  File,
  FileText,
  StickyNote,
  List,
  ListChecks,
  Calendar,
  Clock,
  AlarmClock,
  Hourglass,
  Target,
  Trophy,
  Gift,
  Sparkles,
  WandSparkles,
  Lightbulb,
  Settings,
  Wrench,
  Hammer,
  Puzzle,
  Box,
  Package,
  ShoppingCart,
  CreditCard,
  Banknote,
  ChartBar,
  ChartLine,
  ChartPie,
  AudioWaveform,
  Brain,
  User,
  Users,
  House,
  Building2,
  GraduationCap,
  Book,
  Mail,
  Phone,
  MessageSquare,
  Bell,
  Camera,
  Image,
  Music,
  Gamepad2,
  Plane,
  Car,
  Bike,
  Globe,
  Map,
  MapPin,
  Shield,
  Lock,
  Key,
  Eye,
  LayoutGrid,
  Database,
  Link,
  Palette,
  Keyboard,
  AlarmClockOff,
  SquareArrowOutUpRight,
  Plus,
  X,
  type LucideIcon,
} from "lucide-react";

/** Icons bundled for the picker's Symbol tab and for pins (Lucide, ISC license). Names are Lucide's kebab-case. */
const ICONS: Record<string, LucideIcon> = {
  "star": Star,
  "heart": Heart,
  "zap": Zap,
  "flame": Flame,
  "leaf": Leaf,
  "droplet": Droplet,
  "sun": Sun,
  "moon": Moon,
  "cloud": Cloud,
  "snowflake": Snowflake,
  "circle-check": CircleCheck,
  "circle-x": CircleX,
  "circle-alert": CircleAlert,
  "circle-help": CircleHelp,
  "flag": Flag,
  "bookmark": Bookmark,
  "pin": Pin,
  "tag": Tag,
  "paperclip": Paperclip,
  "folder": Folder,
  "file": File,
  "file-text": FileText,
  "sticky-note": StickyNote,
  "list": List,
  "list-checks": ListChecks,
  "calendar": Calendar,
  "clock": Clock,
  "alarm-clock": AlarmClock,
  "hourglass": Hourglass,
  "target": Target,
  "trophy": Trophy,
  "gift": Gift,
  "sparkles": Sparkles,
  "wand-sparkles": WandSparkles,
  "lightbulb": Lightbulb,
  "settings": Settings,
  "wrench": Wrench,
  "hammer": Hammer,
  "puzzle": Puzzle,
  "box": Box,
  "package": Package,
  "shopping-cart": ShoppingCart,
  "credit-card": CreditCard,
  "banknote": Banknote,
  "chart-bar": ChartBar,
  "chart-line": ChartLine,
  "chart-pie": ChartPie,
  "audio-waveform": AudioWaveform,
  "brain": Brain,
  "user": User,
  "users": Users,
  "house": House,
  "building-2": Building2,
  "graduation-cap": GraduationCap,
  "book": Book,
  "mail": Mail,
  "phone": Phone,
  "message-square": MessageSquare,
  "bell": Bell,
  "camera": Camera,
  "image": Image,
  "music": Music,
  "gamepad-2": Gamepad2,
  "plane": Plane,
  "car": Car,
  "bike": Bike,
  "globe": Globe,
  "map": Map,
  "map-pin": MapPin,
  "shield": Shield,
  "lock": Lock,
  "key": Key,
  "eye": Eye,
  "layout-grid": LayoutGrid,
  "database": Database,
  "link": Link,
  "palette": Palette,
  "keyboard": Keyboard,
  "alarm-clock-off": AlarmClockOff,
  "square-arrow-out-up-right": SquareArrowOutUpRight,
  "plus": Plus,
  "x": X,
};

/** The Symbol tab, in display order (mirrors SymbolCatalog.swift). */
export const LUCIDE_CATALOG: string[] = [
  "star", "heart", "zap", "flame", "leaf", "droplet",
  "sun", "moon", "cloud", "snowflake", "circle-check", "circle-x",
  "circle-alert", "circle-help", "flag", "bookmark", "pin", "tag",
  "paperclip", "folder", "file", "file-text", "sticky-note", "list",
  "list-checks", "calendar", "clock", "alarm-clock", "hourglass", "target",
  "trophy", "gift", "sparkles", "wand-sparkles", "lightbulb", "settings",
  "wrench", "hammer", "puzzle", "box", "package", "shopping-cart",
  "credit-card", "banknote", "chart-bar", "chart-line", "chart-pie", "audio-waveform",
  "brain", "user", "users", "house", "building-2", "graduation-cap",
  "book", "mail", "phone", "message-square", "bell", "camera",
  "image", "music", "gamepad-2", "plane", "car", "bike",
  "globe", "map", "map-pin", "shield", "lock", "key",
  "eye",
];

/** Mac SF Symbol names found in shared JSON, mapped to Lucide (plan 2.6.4). */
const SF_TO_LUCIDE: Record<string, string> = {
  "star.fill": "star", "heart.fill": "heart", "bolt.fill": "zap", "flame.fill": "flame", "leaf.fill": "leaf",
  "drop.fill": "droplet", "sun.max.fill": "sun", "moon.fill": "moon", "cloud.fill": "cloud", snowflake: "snowflake",
  "checkmark.circle.fill": "circle-check", "checkmark.circle": "circle-check", "xmark.circle.fill": "circle-x",
  "exclamationmark.circle.fill": "circle-alert", "questionmark.circle.fill": "circle-help",
  "flag.fill": "flag", "bookmark.fill": "bookmark", "pin.fill": "pin", pin: "pin", "tag.fill": "tag", paperclip: "paperclip",
  "folder.fill": "folder", folder: "folder", "doc.fill": "file", "doc.text.fill": "file-text", "doc.text": "file-text",
  "note.text": "sticky-note", "list.bullet": "list", checklist: "list-checks", calendar: "calendar",
  "clock.fill": "clock", "alarm.fill": "alarm-clock", hourglass: "hourglass", target: "target", "trophy.fill": "trophy",
  "gift.fill": "gift", sparkles: "sparkles", "wand.and.stars": "wand-sparkles", "lightbulb.fill": "lightbulb",
  "gearshape.fill": "settings", gearshape: "settings", "wrench.and.screwdriver.fill": "wrench", "hammer.fill": "hammer",
  "puzzlepiece.fill": "puzzle", "cube.fill": "box", "shippingbox.fill": "package", "cart.fill": "shopping-cart",
  "creditcard.fill": "credit-card", "banknote.fill": "banknote", "chart.bar.fill": "chart-bar",
  "chart.line.uptrend.xyaxis": "chart-line", "chart.pie.fill": "chart-pie", waveform: "audio-waveform",
  "brain.head.profile": "brain", "person.fill": "user", "person.2.fill": "users", "house.fill": "house",
  "building.2.fill": "building-2", "graduationcap.fill": "graduation-cap", "book.fill": "book", "envelope.fill": "mail",
  "phone.fill": "phone", "message.fill": "message-square", "bell.fill": "bell", "camera.fill": "camera",
  "photo.fill": "image", "music.note": "music", "gamecontroller.fill": "gamepad-2", airplane: "plane",
  "car.fill": "car", bicycle: "bike", globe: "globe", "map.fill": "map", "location.fill": "map-pin",
  "shield.fill": "shield", "lock.fill": "lock", "key.fill": "key", "eye.fill": "eye", flame: "flame",
  "cylinder.split.1x2": "database", "square.grid.2x2": "layout-grid", plus: "plus", xmark: "x",
  "arrow.up.right.square": "square-arrow-out-up-right", "moon.zzz": "alarm-clock-off", link: "link",
  paintpalette: "palette", keyboard: "keyboard",
};

/** The Lucide component for a custom-icon name (a Lucide name or a Mac SF Symbol), or null when unknown. */
export function lucideFor(name: string): LucideIcon | null {
  return ICONS[name] ?? ICONS[SF_TO_LUCIDE[name] ?? ""] ?? null;
}

export const lucideName = (name: string): string => (ICONS[name] ? name : (SF_TO_LUCIDE[name] ?? name));
